site_name: Hibiscus
site_description: A lightweight, high-performance study planner and code editor built with React, Tauri, and Rust.
site_author: Andrew Ferns
repo_name: AndyFerns/Hibiscus
site_url: https://andyferns.github.io/Hibiscus/
repo_url: https://github.com/AndyFerns/Hibiscus
use_directory_urls: true
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: assets/logo/128x128.png
  use_directory_urls: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Welcome: index.md

  - Guide:
    - Workspace & Editing:
      - Getting Started: guide/getting-started.md
      - Application Flow: guide/flow.md
      - Workbench: guide/workbench.md
      - Editor: guide/editor.md
      - File Tree: guide/file-tree.md
      - Multi-File Editor: guide/multi-file-editor.md
      - Status Bar: guide/status-bar.md
      - Search System: guide/search.md
    - Knowledge System:
      - Knowledge Dashboard: guide/knowledge-dashboard.md
      - Metadata & Linking: guide/metadata-and-linking.md
      - Knowledge Graph: guide/knowledge-graph.md
      - Modal System: guide/modal-system.md
    - Tools and Productivity:
      - Calender: guide/calendar.md
      - Keyboard Shortcuts: guide/shortcuts.md
      - Theming: guide/theming.md
      - Custom Themes: guide/theme-editor.md
      - Study Tools: guide/study-tools.md

  - Developer:
      - Architecture: dev/architecture.md
      - Dev Hooks: dev/hooks.md
      - Knowledge Pipeline: dev/knowledge-pipeline.md
      - Knowledge Graph Architecture: dev/knowledge-graph-architecture.md
      - Icon System: dev/icon-system.md
      - API Reference: dev/api-reference.md
      - Contributing: dev/contributing.md

  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
